// apps/vue/src/components/TopBar.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { Meta } from '../types';
import { theme, toggleTheme } from '../composables/useTheme';
import FrameworkSwitcher from './FrameworkSwitcher.vue';

const props = defineProps<{ meta: Meta; current: string }>();

// `computed` derives a value from reactive state and caches it until deps change.
const toggleLabel = computed(() => theme.value === 'dark' ? '☀️' : '🌙');
</script>

<template>
  <div class="topbar" role="banner">
    <div class="container">
      <span class="topbar-left">Built with: {{ props.meta.frameworkLabels[props.current] }}</span>
      <div style="display:flex;align-items:center;gap:0.75rem;">
        <FrameworkSwitcher :meta="props.meta" :current="props.current" size="small" />
        <button
          class="theme-toggle"
          :aria-label="`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`"
          title="Toggle dark mode"
          @click="toggleTheme"
        >
          {{ toggleLabel }}
        </button>
      </div>
    </div>
  </div>
</template>

// apps/angular/src/app/components/top-bar.component.ts
import { Component, inject, computed } from '@angular/core';
import { FrameworkSwitcherComponent } from './framework-switcher.component';
import { ContentService } from '../content.service';
import { ThemeService } from '../theme.service';

@Component({
  selector: 'app-top-bar',
  standalone: true,
  imports: [FrameworkSwitcherComponent],
  template: `
    @if (content()) {
      <div class="topbar" role="banner">
        <div class="container">
          <span class="topbar-left">
            Built with: {{ content()!.meta.frameworkLabels['angular'] }}
          </span>
          <div style="display:flex;align-items:center;gap:0.75rem;">
            <app-framework-switcher
              [meta]="content()!.meta"
              [current]="'angular'"
              size="small"
            />
            <button
              class="theme-toggle"
              [attr.aria-label]="'Switch to ' + (themeLabel()) + ' mode'"
              title="Toggle dark mode"
              (click)="themeService.toggle()"
            >{{ toggleIcon() }}</button>
          </div>
        </div>
      </div>
    }
  `,
})
export class TopBarComponent {
  // `inject()` is the functional DI API (Angular 14+) — an alternative to
  // constructor injection that works anywhere inside the injection context.
  contentService = inject(ContentService);
  themeService = inject(ThemeService);

  content = this.contentService.content;

  // `computed` derives a value from signals and memoises it — same as Vue's computed.
  toggleIcon = computed(() => this.themeService.theme() === 'dark' ? '☀️' : '🌙');
  themeLabel = computed(() => this.themeService.theme() === 'dark' ? 'light' : 'dark');
}
