// apps/angular/src/app/app.ts
// Angular components can implement lifecycle interfaces like OnInit.
// `ngOnInit` runs once after the component's inputs are set — the right
// place to trigger data fetching (same role as React's useEffect([]) or
// Vue's onMounted).
import { Component, OnInit, inject } from '@angular/core';
import { initAnimations } from '../../../../shared/animations';
import { ContentService } from './content.service';
import { TopBarComponent } from './components/top-bar.component';
import { HeroSectionComponent } from './components/hero-section.component';
import { AboutSectionComponent } from './components/about-section.component';
import { SkillsSectionComponent } from './components/skills-section.component';
import { ExperienceSectionComponent } from './components/experience-section.component';
import { ProjectsSectionComponent } from './components/projects-section.component';
import { EducationSectionComponent } from './components/education-section.component';
import { AboutSiteSectionComponent } from './components/about-site-section.component';
import { FooterSectionComponent } from './components/footer-section.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    TopBarComponent,
    HeroSectionComponent,
    AboutSectionComponent,
    SkillsSectionComponent,
    ExperienceSectionComponent,
    ProjectsSectionComponent,
    EducationSectionComponent,
    AboutSiteSectionComponent,
    FooterSectionComponent,
  ],
  template: `
    @if (contentService.error()) {
      <div style="padding:2rem;color:red;">
        Failed to load portfolio content: {{ contentService.error() }}
      </div>
    }
    @if (contentService.content(); as content) {
      <app-top-bar />
      <main id="main-content">
        <app-hero-section [profile]="content.profile" />
        <app-about-section [summary]="content.summary" />
        <app-skills-section [skills]="content.skills" />
        <app-experience-section [experience]="content.experience" />
        <app-projects-section [projects]="content.projects" />
        <app-education-section [education]="content.education" />
        <app-about-site-section [meta]="content.meta" [current]="'angular'" [aboutSite]="content.aboutSite" />
      </main>
      <app-footer-section [profile]="content.profile" />
    }
  `,
})
export class App implements OnInit {
  contentService = inject(ContentService);

  ngOnInit(): void {
    this.contentService.load().then(() => {
      const content = this.contentService.content();
      if (content) {
        document.title = content.meta.siteTitle;
        const metaDesc = document.querySelector<HTMLMetaElement>('meta[name="description"]');
        if (metaDesc) metaDesc.content = content.meta.description;
      }
      // setTimeout defers until after Angular's change-detection render cycle
      setTimeout(() => initAnimations(content?.profile.taglines));
    });
  }
}

// apps/vue/src/App.vue
<script setup lang="ts">
// `ref` holds reactive state. When `content.value` is set, Vue re-renders
// any template that reads it — no manual DOM updates needed.
import { ref, onMounted, nextTick } from 'vue';
import type { Content } from './types';
import { fetchContent } from '../../../shared/fetchContent';
import { initAnimations } from '../../../shared/animations';
import TopBar from './components/TopBar.vue';
import HeroSection from './components/HeroSection.vue';
import AboutSection from './components/AboutSection.vue';
import SkillsSection from './components/SkillsSection.vue';
import ExperienceSection from './components/ExperienceSection.vue';
import ProjectsSection from './components/ProjectsSection.vue';
import EducationSection from './components/EducationSection.vue';
import AboutSiteSection from './components/AboutSiteSection.vue';
import FooterSection from './components/FooterSection.vue';

const content = ref<Content | null>(null);
const error = ref<string | null>(null);

// `onMounted` runs after the component is inserted into the DOM —
// the right place for side effects like data fetching.
onMounted(async () => {
  try {
    content.value = await fetchContent();
    await nextTick();
    initAnimations(content.value.profile.taglines);

    if (content.value) {
      document.title = content.value.meta.siteTitle;
      const metaDesc = document.querySelector<HTMLMetaElement>('meta[name="description"]');
      if (metaDesc) metaDesc.content = content.value.meta.description;
    }
  } catch (e) {
    error.value = (e as Error).message;
  }
});
</script>

<template>
  <div v-if="error" style="padding:2rem;color:red;">
    Failed to load portfolio content: {{ error }}
  </div>

  <!-- v-else-if renders only when content has loaded (non-null) -->
  <div v-else-if="content">
    <TopBar :meta="content.meta" :current="'vue'" />
    <main id="main-content">
      <HeroSection :profile="content.profile" />
      <AboutSection :summary="content.summary" />
      <SkillsSection :skills="content.skills" />
      <ExperienceSection :experience="content.experience" />
      <ProjectsSection :projects="content.projects" />
      <EducationSection :education="content.education" />
      <AboutSiteSection :meta="content.meta" :current="'vue'" :aboutSite="content.aboutSite" />
    </main>
    <FooterSection :profile="content.profile" />
  </div>
</template>
