// apps/react/src/App.tsx
// React components are plain functions that return JSX.
// `useState` and `useEffect` are the two core hooks:
//   - useState: reactive value + setter (triggers re-render on change)
//   - useEffect: side effects after render (data fetch, DOM updates, subscriptions)
import { useState, useEffect } from 'react';
import type { Content } from './types';
import { useTheme } from './hooks/useTheme';
import { TopBar } from './components/TopBar';
import { HeroSection } from './components/HeroSection';
import { AboutSection } from './components/AboutSection';
import { SkillsSection } from './components/SkillsSection';
import { ExperienceSection } from './components/ExperienceSection';
import { ProjectsSection } from './components/ProjectsSection';
import { EducationSection } from './components/EducationSection';
import { AboutSiteSection } from './components/AboutSiteSection';
import { FooterSection } from './components/FooterSection';

function App() {
  const [content, setContent] = useState<Content | null>(null);
  const [error, setError] = useState<string | null>(null);
  const { theme, toggleTheme } = useTheme();

  // Empty dependency array `[]` means this runs once after the first render —
  // equivalent to Vue's `onMounted`.
  useEffect(() => {
    const url = new URL('content.json', document.baseURI);
    fetch(url.href)
      .then(res => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json() as Promise<Content>;
      })
      .then(data => {
        setContent(data);
        document.title = data.meta.siteTitle;
        const metaDesc = document.querySelector<HTMLMetaElement>('meta[name="description"]');
        if (metaDesc) metaDesc.content = data.meta.description;
      })
      .catch((e: Error) => setError(e.message));
  }, []);

  if (error) {
    return <div style={{ padding: '2rem', color: 'red' }}>Failed to load portfolio content: {error}</div>;
  }

  if (!content) return null;

  return (
    <>
      <TopBar
        meta={content.meta}
        current={content.meta.defaultFramework}
        theme={theme}
        onToggleTheme={toggleTheme}
      />
      <main id="main-content">
        <HeroSection profile={content.profile} />
        <AboutSection summary={content.summary} />
        <SkillsSection skills={content.skills} />
        <ExperienceSection experience={content.experience} />
        <ProjectsSection projects={content.projects} />
        <EducationSection education={content.education} />
        <AboutSiteSection meta={content.meta} current={content.meta.defaultFramework} />
      </main>
      <FooterSection profile={content.profile} />
    </>
  );
}

export default App;

// apps/vue/src/App.vue
<script setup lang="ts">
// `ref` holds reactive state. When `content.value` is set, Vue re-renders
// any template that reads it — no manual DOM updates needed.
import { ref, onMounted } from 'vue';
import type { Content } from './types';
import TopBar from './components/TopBar.vue';
import HeroSection from './components/HeroSection.vue';
import AboutSection from './components/AboutSection.vue';
import SkillsSection from './components/SkillsSection.vue';
import ExperienceSection from './components/ExperienceSection.vue';
import ProjectsSection from './components/ProjectsSection.vue';
import EducationSection from './components/EducationSection.vue';
import AboutSiteSection from './components/AboutSiteSection.vue';
import FooterSection from './components/FooterSection.vue';

const content = ref<Content | null>(null);
const error = ref<string | null>(null);

// `onMounted` runs after the component is inserted into the DOM —
// the right place for side effects like data fetching.
onMounted(async () => {
  try {
    const url = new URL('content.json', document.baseURI);
    const res = await fetch(url.href);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    content.value = await res.json();

    if (content.value) {
      document.title = content.value.meta.siteTitle;
      const metaDesc = document.querySelector<HTMLMetaElement>('meta[name="description"]');
      if (metaDesc) metaDesc.content = content.value.meta.description;
    }
  } catch (e) {
    error.value = (e as Error).message;
  }
});
</script>

<template>
  <div v-if="error" style="padding:2rem;color:red;">
    Failed to load portfolio content: {{ error }}
  </div>

  <!-- v-else-if renders only when content has loaded (non-null) -->
  <div v-else-if="content">
    <TopBar :meta="content.meta" :current="content.meta.defaultFramework" />
    <main id="main-content">
      <HeroSection :profile="content.profile" />
      <AboutSection :summary="content.summary" />
      <SkillsSection :skills="content.skills" />
      <ExperienceSection :experience="content.experience" />
      <ProjectsSection :projects="content.projects" />
      <EducationSection :education="content.education" />
      <AboutSiteSection :meta="content.meta" :current="content.meta.defaultFramework" />
    </main>
    <FooterSection :profile="content.profile" />
  </div>
</template>
