// apps/vue/src/components/AboutSection.vue
<script setup lang="ts">
defineProps<{ summary: string }>();
</script>

<template>
  <section class="section" id="about" aria-labelledby="about-heading">
    <div class="container">
      <h2 class="section-heading" id="about-heading">About</h2>
      <p>{{ summary }}</p>
    </div>
  </section>
</template>

// apps/react/src/components/AboutSection.tsx
export function AboutSection({ summary }: { summary: string }) {
  return (
    <section className="section" id="about" aria-labelledby="about-heading">
      <div className="container">
        <h2 className="section-heading" id="about-heading">About</h2>
        <p>{summary}</p>
      </div>
    </section>
  );
}
