// apps/angular/src/app/components/about-section.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-about-section',
  standalone: true,
  template: `
    <section class="section" id="about" aria-labelledby="about-heading">
      <div class="container">
        <h2 class="section-heading" id="about-heading">About</h2>
        <p>{{ summary() }}</p>
      </div>
    </section>
  `,
})
export class AboutSectionComponent {
  summary = input.required<string>();
}

// apps/react/src/components/AboutSection.tsx
export function AboutSection({ summary }: { summary: string }) {
  return (
    <section className="section" id="about" aria-labelledby="about-heading">
      <div className="container">
        <h2 className="section-heading" id="about-heading">About</h2>
        <p>{summary}</p>
      </div>
    </section>
  );
}
