// apps/vue/src/components/FrameworkSwitcher.vue
<script setup lang="ts">
// `defineProps` declares typed props — no `return` needed with <script setup>;
// everything declared here is automatically available in the template below.
import type { Meta } from '../types';

const props = defineProps<{
  meta: Meta;
  current: string;
  size?: 'small' | 'large';
}>();
</script>

<template>
  <!-- v-bind:class (shorthand :class) sets the CSS class reactively -->
  <nav
    :class="props.size === 'large' ? 'fw-switcher-large' : 'fw-switcher'"
    aria-label="Framework versions"
  >
    <!-- v-for iterates the array; :key is required for Vue's diff algorithm -->
    <template v-for="fw in props.meta.frameworks" :key="fw">
      <!-- v-if / v-else are structural directives that conditionally render -->
      <span v-if="fw === props.current" aria-current="page">
        {{ props.meta.frameworkLabels[fw] }}
      </span>
      <a v-else :href="props.meta.frameworkPaths[fw]">
        {{ props.meta.frameworkLabels[fw] }}
      </a>
    </template>
  </nav>
</template>

// apps/react/src/components/FrameworkSwitcher.tsx
// In React, a component is just a function that returns JSX.
// Props are typed via an interface and destructured in the parameter list.
import type { Meta } from '../types';

interface Props {
  meta: Meta;
  current: string;
  size?: 'small' | 'large';
}

export function FrameworkSwitcher({ meta, current, size = 'small' }: Props) {
  const cls = size === 'large' ? 'fw-switcher-large' : 'fw-switcher';

  return (
    <nav className={cls} aria-label="Framework versions">
      {/* JSX uses `className` instead of `class` (class is reserved in JS) */}
      {meta.frameworks.map(fw =>
        fw === current ? (
          <span key={fw} aria-current="page">{meta.frameworkLabels[fw]}</span>
        ) : (
          <a key={fw} href={meta.frameworkPaths[fw]}>{meta.frameworkLabels[fw]}</a>
        )
      )}
    </nav>
  );
}
