// apps/vue/src/components/ProjectsSection.vue
<script setup lang="ts">
import type { Project } from '../types';
defineProps<{ projects: Project[] }>();
</script>

<template>
  <section class="section" id="projects" aria-labelledby="projects-heading">
    <div class="container">
      <h2 class="section-heading" id="projects-heading">Projects</h2>
      <div class="projects-grid">
        <article v-for="project in projects" :key="project.name" class="project-card">
          <div class="project-card-header">
            <span class="project-name">{{ project.name }}</span>
            <span class="project-date">{{ project.date }}</span>
          </div>
          <a
            v-if="project.url"
            :href="project.url"
            class="project-link"
            target="_blank"
            rel="noopener noreferrer"
          >↗ Visit</a>
          <ul class="project-bullets">
            <li v-for="(bullet, i) in project.bullets" :key="i">{{ bullet }}</li>
          </ul>
        </article>
      </div>
    </div>
  </section>
</template>

// apps/react/src/components/ProjectsSection.tsx
import type { Project } from '../types';

export function ProjectsSection({ projects }: { projects: Project[] }) {
  return (
    <section className="section" id="projects" aria-labelledby="projects-heading">
      <div className="container">
        <h2 className="section-heading" id="projects-heading">Projects</h2>
        <div className="projects-grid">
          {projects.map(project => (
            <article key={project.name} className="project-card">
              <div className="project-card-header">
                <span className="project-name">{project.name}</span>
                <span className="project-date">{project.date}</span>
              </div>
              {project.url && (
                <a className="project-link" href={project.url} target="_blank" rel="noopener noreferrer">
                  ↗ Visit
                </a>
              )}
              <ul className="project-bullets">
                {project.bullets.map((bullet, i) => <li key={i}>{bullet}</li>)}
              </ul>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
