// apps/react/src/components/ExperienceSection.tsx
import type { Company } from '../types';

export function ExperienceSection({ experience }: { experience: Company[] }) {
  return (
    <section className="section" id="experience" aria-labelledby="experience-heading">
      <div className="container">
        <h2 className="section-heading" id="experience-heading">Experience</h2>
        {experience.map(company => (
          <div key={company.company} className="experience-company">
            <div className="company-header">
              <span className="company-name">{company.company}</span>
              <span className="company-location">{company.location}</span>
            </div>
            {company.roles.map(role => (
              <div key={role.title + role.start} className="role">
                <div className="role-header">
                  <span className="role-title">{role.title}</span>
                  <span className="role-dates">{role.start} – {role.end}</span>
                </div>
                <ul className="role-bullets">
                  {role.bullets.map((bullet, i) => <li key={i}>{bullet}</li>)}
                </ul>
              </div>
            ))}
          </div>
        ))}
      </div>
    </section>
  );
}

// apps/vue/src/components/ExperienceSection.vue
<script setup lang="ts">
import type { Company } from '../types';
defineProps<{ experience: Company[] }>();
</script>

<template>
  <section class="section" id="experience" aria-labelledby="experience-heading">
    <div class="container">
      <h2 class="section-heading" id="experience-heading">Experience</h2>
      <div v-for="company in experience" :key="company.company" class="experience-company">
        <div class="company-header">
          <span class="company-name">{{ company.company }}</span>
          <span class="company-location">{{ company.location }}</span>
        </div>
        <div v-for="role in company.roles" :key="role.title + role.start" class="role">
          <div class="role-header">
            <span class="role-title">{{ role.title }}</span>
            <span class="role-dates">{{ role.start }} – {{ role.end }}</span>
          </div>
          <ul class="role-bullets">
            <li v-for="(bullet, i) in role.bullets" :key="i">{{ bullet }}</li>
          </ul>
        </div>
      </div>
    </div>
  </section>
</template>
