// apps/react/src/components/TopBar.tsx
import type { Meta } from '../types';
import { FrameworkSwitcher } from './FrameworkSwitcher';

interface Props {
  meta: Meta;
  current: string;
  theme: 'light' | 'dark';
  onToggleTheme: () => void;
}

export function TopBar({ meta, current, theme, onToggleTheme }: Props) {
  return (
    <div className="topbar" role="banner">
      <div className="container">
        <span className="topbar-left">Built with: {meta.frameworkLabels[current]}</span>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <FrameworkSwitcher meta={meta} current={current} size="small" />
          <button
            className="theme-toggle"
            aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`}
            title="Toggle dark mode"
            onClick={onToggleTheme}
          >
            {theme === 'dark' ? '☀️' : '🌙'}
          </button>
        </div>
      </div>
    </div>
  );
}

// apps/vue/src/components/TopBar.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { Meta } from '../types';
import { theme, toggleTheme } from '../composables/useTheme';
import FrameworkSwitcher from './FrameworkSwitcher.vue';

const props = defineProps<{ meta: Meta; current: string }>();

// `computed` derives a value from reactive state and caches it until deps change.
const toggleLabel = computed(() => theme.value === 'dark' ? '☀️' : '🌙');
</script>

<template>
  <div class="topbar" role="banner">
    <div class="container">
      <span class="topbar-left">Built with: {{ props.meta.frameworkLabels[props.current] }}</span>
      <div style="display:flex;align-items:center;gap:0.75rem;">
        <FrameworkSwitcher :meta="props.meta" :current="props.current" size="small" />
        <button
          class="theme-toggle"
          :aria-label="`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`"
          title="Toggle dark mode"
          @click="toggleTheme"
        >
          {{ toggleLabel }}
        </button>
      </div>
    </div>
  </div>
</template>
